import Head from 'next/head'
import Image from 'next/image'
import NavBar from './components/NavBar'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import JobSearchService from './services/JobSearchService'


export default function Home() {
  const [recentlyAppliedData, setRecentlyAppliedData] = useState([])
  const recentlyApplied = []
  useEffect(() => {
    JobSearchService.getJobSearches().then((res) => {
      for (let i = recentlyAppliedData.length; i >= 0; i--) {
        recentlyApplied.push(res.data[i].dateApplied)
      }
      setRecentlyAppliedData([recentlyApplied])
      console.log(recentlyAppliedData)
    });
  }, [0]);

  return (
    <div>
      <Head>
        <title>JobHunter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jobhunterlogo.svg" />
      </Head>
      <header>
        <NavBar />
      </header>
      <main>
        <section className="landing-section">
          <h1 className="landing-section-heading">Recently Applied</h1>
          <div id="recently-applied-section" className="landing-section-container">
            {recentlyAppliedData === '' ? null : 
            recentlyAppliedData.map(recent =>
            <div className="recently-applied">
              <p>Date Applied: {recent.recentlyApplied}</p>
              <p>Job Title - Company Name</p>
              <p>Job Posting Url</p>
              <p>More Info</p>
            </div>)}

          </div>
          <div className="landing-add-search-section">
            <span>Add New Search</span>
            <Link href="/Add-Search"><a><button className="landing-add-btn">✚</button></a></Link>
          </div>
        </section>
        <hr />
        <section id="status-check-section" className="landing-section">
          <h1 className="landing-section-heading">Status Check</h1>

          <div id="status-check-section" className="landing-section-container">
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard1" />
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard2" />
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard3" />
          </div>
        </section>
        <hr />

        {/* <ListJobSearches /> */}
        {/* <AddSearch /> */}
        {/* <UpdateJobSearch /> */}
        {/* <DeleteJobSearch /> */}
      </main>
    </div >
  )
}
