import Head from 'next/head'
import Image from 'next/image'
import NavBar from './components/NavBar'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import JobSearchService from './services/JobSearchService'


export default function Home() {
  const [recentlyAppliedData, setRecentlyAppliedData] = useState([])
  useEffect(() => {
    JobSearchService.getJobSearches().then((res) => {
      setRecentlyAppliedData(res.data)
    });
  }, [3]);
  console.log(recentlyAppliedData)
  return (
    <div>
      <Head>
        <title>JobHunter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jobhunterlogo.svg" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"></link>
      </Head>
      <header>
        <NavBar />
      </header>
      <main>
        <section className="landing-section">
          <h1 className="landing-section-heading">Recently Applied</h1>
          <div id="recently-applied-section" className="landing-section-container">
            {recentlyAppliedData.reverse().map((recent, index) => index > 2 ? null :
              <div className="recently-applied">
                <p><span>Date Applied:</span> {recent.dateApplied}</p>
                <p><span>Job Title:</span> {recent.jobTitle}</p>
                <p><span>Company Name:</span> {recent.name}</p>
                <p><span>Job Posting URL:</span> {recent.jobPostingURL}</p>
                <Link href="/Manage-Searches"><button>More Info</button></Link>
              </div>
            )}
          </div>
          <div className="landing-add-search-section">
            <span>Add New Search</span>
            <Link href="/Add-Search"><a><button className="landing-add-btn">✚</button></a></Link>
          </div>
        </section>
        <hr />
        <section id="status-check-section" className="landing-section">
          <h1 className="landing-section-heading">Status Check</h1>

          <div id="status-check-section" className="landing-section-container">
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard1" />
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard2" />
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard3" />
          </div>
        </section>
        <hr />
        <section className="landing-section">
          <h1 className="landing-section-heading">Manage Searches</h1>

          <div id="manage-searches-section" className="landing-section-container">
            <div className="landing-manage-add landing-manage">
              <p className="landing-manage-heading">Add Search</p>
              <Link href="/Add-Job-Search"><button><i class="fas fa-plus"></i></button></Link>

            </div>
            <div className="landing-manage-update landing-manage">
              <p className="landing-manage-heading">Update Search</p>
              <Link href="/Manage-Searches"><button><i className="fas fa-sync-alt"></i></button></Link>
            </div>
            <div className="landing-manage-delete landing-manage">
              <p className="landing-manage-heading">Delete Search</p>
              <Link href="/Manage-Searches"><button><i className="fas fa-trash-alt"></i></button></Link>
            </div>
          </div>
        </section>
      </main>
    </div >
  )
}
