import Head from 'next/head'
import Image from 'next/image'
import NavBar from './components/NavBar'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import JobSearchService from './services/JobSearchService'


export default function Home() {
  const [recentlyAppliedData, setRecentlyAppliedData] = useState([])
  useEffect(() => {
    JobSearchService.getJobSearches().then((res) => {
      setRecentlyAppliedData(res.data)
    });
  }, [3]);
  console.log(recentlyAppliedData)
  return (
    <div>
      <Head>
        <title>JobHunter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jobhunterlogo.svg" />
      </Head>
      <header>
        <NavBar />
      </header>
      <main>
        <section className="landing-section">
          <h1 className="landing-section-heading">Recently Applied</h1>
          <div id="recently-applied-section" className="landing-section-container">
            {recentlyAppliedData.reverse().map((recent, index) => index > 2 ? null :
              <div className="recently-applied">
                <p>Date Applied: {recent.dateApplied}</p>
                <p>{recent.jobTitle} - {recent.name}</p>
                <p>{recent.jobPostingURL}</p>
                <p>More Info</p>
              </div>
 )}
          </div>
          <div className="landing-add-search-section">
            <span>Add New Search</span>
            <Link href="/Add-Search"><a><button className="landing-add-btn">✚</button></a></Link>
          </div>
        </section>
        <hr />
        <section id="status-check-section" className="landing-section">
          <h1 className="landing-section-heading">Status Check</h1>

          <div id="status-check-section" className="landing-section-container">
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard1" />
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard2" />
            <Image src="/clipboard.png" width="375vw" height="450vh" id="clipboard3" />
          </div>
        </section>
        <hr />

        {/* <ListJobSearches /> */}
        {/* <AddSearch /> */}
        {/* <UpdateJobSearch /> */}
        {/* <DeleteJobSearch /> */}
      </main>
    </div >
  )
}
